# Generated by Django 4.2.6 on 2023-10-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DAL', '0002_employee_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_manager',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
